{% set name = "Flask-User" %}
{% set version = "1.0.1.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "3b17b1d2714d8fda9754a717ab6500dc88981f68fda4a19294381dee429b2c0f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - flask-login

  run:
    - python
    - passlib >=1.6
    - bcrypt >=2.0
    - cryptography >=1.6
    - flask >=0.9
    - flask-login >=0.2
    - flask-mail >=0.9
    - flask-sqlalchemy >=1.0
    - flask-wtf >=0.9

test:
  imports:
    - flask_user

about:
  home: http://github.com/lingthio/Flask-User
  license: BSD 2-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: 'Customizable User Account Management for Flask: Register, Confirm email, Login, Change username, Change password, Forgot password and more.'
  dev_url: http://github.com/lingthio/Flask-User
  doc_url: https://pythonhosted.org/Flask-User/

extra:
  recipe-maintainers:
    - pmlandwehr
