{% set name = "Flask-User" %}
{% set version = "1.0.1.1" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "b14fa9e60d9d38da6fd9ae04f4aa7cc07e575db82800321ebfbb116291a88e15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
    - flask-login

  run:
    - python
    - passlib
    - bcrypt
    - pycryptodome
    - flask
    - flask-login
    - flask-mail
    - flask-sqlalchemy
    - flask-wtf

test:
  imports:
    - flask_user

about:
  home: http://github.com/lingthio/Flask-User
  license: BSD 2-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: 'Customizable User Account Management for Flask: Register, Confirm email, Login, Change username, Change password, Forgot password and more.'
  dev_url: http://github.com/lingthio/Flask-User
  doc_url: https://pythonhosted.org/Flask-User/

extra:
  recipe-maintainers:
    - pmlandwehr
