{% set name = "Flask-User" %}
{% set version = "1.0.2.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "79fec026a6ba0e06159e51ceeb4b88c993d7f026a4b6c6e448cb0cc40d7473ae" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - flask-login

  run:
    - python
    - passlib >=1.6
    - bcrypt >=2.0
    - cryptography >=1.6
    - flask >=0.9
    - flask-login >=0.2
    - flask-mail >=0.9
    - flask-sqlalchemy >=1.0
    - flask-wtf >=0.9

test:
  imports:
    - flask_user

about:
  home: http://github.com/lingthio/Flask-User
  license: BSD 2-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: 'Customizable User Account Management for Flask: Register, Confirm email, Login, Change username, Change password, Forgot password and more.'
  dev_url: http://github.com/lingthio/Flask-User
  doc_url: https://pythonhosted.org/Flask-User/

extra:
  recipe-maintainers:
    - pmlandwehr
