travis:
  secure:
    BINSTAR_TOKEN: E3vfO4XN+Htww5eGRo0K/RZi8ZmHALOvoKss//9WZtZGzTpnW46MhbC22BtNslBF3U7w543cU270mADSxLVrC+pBK8yi55dA6WUrh4JeXXmH2R07jM8ftsp6TnYtGMey/oT4SlzF6OH1Cs8sQpTrhzDVwipFNi/+fELkNccs2SOBLiR/eHhG2Si9cEet1wBfJ2t/69a4tlpid69tGIWRaJEZ1v7btL4RyHFQTQISNurSocAsmhWzWm19eAVbMdkEWsmHDRqQrhlHXMR8W5n+7fETqvkE1LPYHH5EpedMTHZPxjdXl18YQ4Lsf/XeTuyY/vc9eiflps2ZzN2lDtTX60RwZMmu7zjQUIyaWMIFFN3jvK+duesutyXm/Dn4aK3GtqVSiVL/GcDDSID65Kp64OkrCDQq19daTpiiHoz3aGPj1j/UI3D6YNefofAVdqZNHVtqI7HKyXDdU9Pygwou7Na1yPdbi6eQ4afMVaDXBzv4yyVTXX0TxG+RHCNbOxv6BdElZWSBCv1ArTksYw6STKlqlaaSEPWw5AmP5/UJu3Ser1oq7Q4y9TAWwTK7MNXqYpfIM4DCwU+E4UCVToggvr394tIqaZ271wa6qr8QgXlX4/i54nkKuuD+jzFQoniypPV9dI1Nl2WP0PzIvm/wZaAUytK+Cl0L/rBc02a6V7w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
