travis:
  secure:
    BINSTAR_TOKEN: A5ciYNGNGlS+5zji8yDEghmz5g4vNG2FnOyOtQPpfH0KsbYdZv80VcySsikfQytJMbJ3ibzE2aOsR4wTVX6OXmWGBoCE9uNtvst+RN25YmKoHl7G+3Z/IyM3ar7yNp6NVQpoL3hb+CeqEArFd5/vGrXnKykPUrDfdLtFOeuzsUeQwdOR7n00b428icMcEVtIpP59W7g9q3zXTQ9vODwWmSwlSUZnycc7+dLttDgQA92kXADkcJusoBhgnH3xc/AbVRV7THbaIs7/M7Hr9qMQJG0CuVautLeUhvS5fIMuY2/jBLYHgD8Phll6kLHLmYded72FM7BiEifJL/VVbqT4X2GaNODBA83ZG+Y6j2qzBFW5JdJTfA5s4FT29FueyuPrpQ+r4zDMwXq6RMrzeeAvvjJLezEiBoz+O11r9Td0dhu6S7X3xeq5ej5V1pdtOs7aB6K4CGG6kC266h58hy1jzzw7orHVtGLSMV7j9TduETVeJrLD6Cpl5sWSJJ3jdq150qbaBG/BCzxoVBAqlwu3WVZZyBFGO+Jfkm+BhNdNWNeUDOotdH9ytSN8wnO7NXOwzzHTkocKRPBFqOayO601Nemvv5F9CW5/fqsM+Uxpxbv/U0Mjmi+CL80TIdZfhVQV7IKeiTKhNjnc5xLUAFc4vJ5VGPkrg22C71LEV9DtcL4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
